// <auto-generated />
using System;
using ForecastingModelParameters.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForecastingModelParameters.Infrastructure.Repositories.MSSql.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260821173423_DatabaseOptimization")]
    partial class DatabaseOptimization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForecastingModelParameters.Domain.ConstructionCostByPeriod", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConstructionCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Property")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("RowId");

                    b.ToTable("ConstructionCostByPeriods", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ConstructionCostByProperty", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConstructionCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncurredCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Property")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RowId");

                    b.ToTable("ConstructionCostByProperties", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.OtherCost", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IncurredCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sheet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RowId");

                    b.ToTable("OtherCosts", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.OtherCostByPeriod", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MoneyIn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MoneyOut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("RowId");

                    b.ToTable("OtherCostByPeriods", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.SalesValueByCategory", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalesValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sold")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RowId");

                    b.ToTable("SalesValueByCategories", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.SalesValueByPeriod", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<decimal>("SalesValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("RowId");

                    b.ToTable("SalesValueByPeriods", "params");
                });
#pragma warning restore 612, 618
        }
    }
}
