// <auto-generated />
using System;
using ForecastingModelParameters.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForecastingModelParameters.Infrastructure.Repositories.MSSql.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260915125703_ReworkingForecastingModel")]
    partial class ReworkingForecastingModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForecastingModelParameters.Domain.ComplexProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectForecastId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectForecastId")
                        .IsUnique();

                    b.ToTable("DimComplexProperties", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.CostItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("FlowDirection")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectForecastId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectForecastId")
                        .IsUnique();

                    b.ToTable("DimCostItems", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.Date", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectForecastId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectForecastId")
                        .IsUnique();

                    b.ToTable("DimDates", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.LoanTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("EscrowFunding")
                        .HasColumnType("float");

                    b.Property<double>("InterestPayable")
                        .HasColumnType("float");

                    b.Property<double>("KeyRate")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Principal")
                        .HasColumnType("float");

                    b.Property<Guid>("ProjectForecastId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectForecastId")
                        .IsUnique();

                    b.ToTable("DimLoanTerms", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ProjectCostingData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fact")
                        .HasColumnType("float");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectCostingDatas", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ProjectCostingDataPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<Guid>("ProjectCostingDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Quarter")
                        .HasColumnType("float");

                    b.Property<double>("Year")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCostingDataId");

                    b.ToTable("ProjectCostingDataPeriods", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ProjectForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ComplexPropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CostItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoanTermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FactProjectForecasts", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommissioningOfResidentialProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectForecastId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectForecastId")
                        .IsUnique();

                    b.ToTable("DimProperties", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ReportField", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConstructionCostForecast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Parameter")
                        .HasColumnType("bit");

                    b.Property<string>("ReportSheet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RowId");

                    b.ToTable("ReportFields", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ComplexProperty", b =>
                {
                    b.HasOne("ForecastingModelParameters.Domain.ProjectForecast", "ProjectForecast")
                        .WithOne("ComplexProperty")
                        .HasForeignKey("ForecastingModelParameters.Domain.ComplexProperty", "ProjectForecastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectForecast");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.CostItem", b =>
                {
                    b.HasOne("ForecastingModelParameters.Domain.ProjectForecast", "ProjectForecast")
                        .WithOne("CostItem")
                        .HasForeignKey("ForecastingModelParameters.Domain.CostItem", "ProjectForecastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectForecast");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.Date", b =>
                {
                    b.HasOne("ForecastingModelParameters.Domain.ProjectForecast", "ProjectForecast")
                        .WithOne("Date")
                        .HasForeignKey("ForecastingModelParameters.Domain.Date", "ProjectForecastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectForecast");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.LoanTerm", b =>
                {
                    b.HasOne("ForecastingModelParameters.Domain.ProjectForecast", "ProjectForecast")
                        .WithOne("LoanTerm")
                        .HasForeignKey("ForecastingModelParameters.Domain.LoanTerm", "ProjectForecastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectForecast");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ProjectCostingDataPeriod", b =>
                {
                    b.HasOne("ForecastingModelParameters.Domain.ProjectCostingData", "ProjectCostingData")
                        .WithMany("ProjectCostingDataPeriods")
                        .HasForeignKey("ProjectCostingDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectCostingData");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.Property", b =>
                {
                    b.HasOne("ForecastingModelParameters.Domain.ProjectForecast", "ProjectForecast")
                        .WithOne("Property")
                        .HasForeignKey("ForecastingModelParameters.Domain.Property", "ProjectForecastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectForecast");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ProjectCostingData", b =>
                {
                    b.Navigation("ProjectCostingDataPeriods");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ProjectForecast", b =>
                {
                    b.Navigation("ComplexProperty");

                    b.Navigation("CostItem");

                    b.Navigation("Date");

                    b.Navigation("LoanTerm");

                    b.Navigation("Property");
                });
#pragma warning restore 612, 618
        }
    }
}
