// <auto-generated />
using System;
using ForecastingModelParameters.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForecastingModelParameters.Infrastructure.Repositories.MSSql.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260918054957_Redesignedstructure")]
    partial class Redesignedstructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForecastingModelParameters.Domain.ComplexProperty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DimComplexProperties", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.CostItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FlowDirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DimCostItems", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.Date", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DimDates", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ProjectCostingData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fact")
                        .HasColumnType("float");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectCostingDatas", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ProjectCostingDataPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<Guid>("ProjectCostingDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Quarter")
                        .HasColumnType("float");

                    b.Property<double>("Year")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCostingDataId");

                    b.ToTable("ProjectCostingDataPeriods", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ProjectForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ComplexPropertyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostItemId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FactProjectForecasts", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.Property", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommissioningOfResidentialProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DimProperties", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ReportField", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConstructionCostForecast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Parameter")
                        .HasColumnType("bit");

                    b.Property<string>("ReportSheet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RowId");

                    b.ToTable("ReportFields", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ProjectCostingDataPeriod", b =>
                {
                    b.HasOne("ForecastingModelParameters.Domain.ProjectCostingData", "ProjectCostingData")
                        .WithMany("ProjectCostingDataPeriods")
                        .HasForeignKey("ProjectCostingDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectCostingData");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ProjectCostingData", b =>
                {
                    b.Navigation("ProjectCostingDataPeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
