// <auto-generated />
using System;
using ForecastingModelParameters.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForecastingModelParameters.Infrastructure.Repositories.MSSql.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260819122730_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForecastingModelParameters.Domain.ConstructionCostByProperty", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConstructionCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncurredCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Property")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RowId");

                    b.ToTable("ConstructionCostByProperties", "Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
