// <auto-generated />
using System;
using ForecastingModelParameters.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForecastingModelParameters.Infrastructure.Repositories.MSSql.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260902103102_ReplacedDecimalWithDouble")]
    partial class ReplacedDecimalWithDouble
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForecastingModelParameters.Domain.ConstructionCostByPeriod", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CommissioningOfResidentialProperty")
                        .HasColumnType("bit");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ConstructionCost")
                        .HasColumnType("float");

                    b.Property<double>("PercentageOfCosts")
                        .HasPrecision(18, 4)
                        .HasColumnType("float(18)");

                    b.Property<string>("Property")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quarter")
                        .HasColumnType("float");

                    b.Property<double>("Year")
                        .HasColumnType("float");

                    b.HasKey("RowId");

                    b.ToTable("ConstructionCostByPeriods", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ConstructionCostByProperty", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IncurredCosts")
                        .HasColumnType("float");

                    b.Property<double>("PlannedCostPerSqm")
                        .HasColumnType("float");

                    b.Property<string>("Property")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SquareMeters")
                        .HasColumnType("float");

                    b.HasKey("RowId");

                    b.ToTable("ConstructionCostByProperties", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.OtherFixedCost", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IncurredCosts")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RowId");

                    b.ToTable("OtherFixedCosts", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.OtherFixedCostByPeriod", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quarter")
                        .HasColumnType("float");

                    b.Property<double>("Year")
                        .HasColumnType("float");

                    b.HasKey("RowId");

                    b.ToTable("OtherFixedCostByPeriods", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.OtherPercentageCost", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PercentageOfCosts")
                        .HasPrecision(18, 4)
                        .HasColumnType("float(18)");

                    b.Property<bool>("ResidentialProperty")
                        .HasColumnType("bit");

                    b.HasKey("RowId");

                    b.ToTable("OtherPercentageCosts", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.OtherPercentageCostByPeriod", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PercentageOfCosts")
                        .HasPrecision(18, 4)
                        .HasColumnType("float(18)");

                    b.Property<double>("Quarter")
                        .HasColumnType("float");

                    b.Property<double>("Year")
                        .HasColumnType("float");

                    b.HasKey("RowId");

                    b.ToTable("OtherPercentageCostByPeriods", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.ReportField", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConstructionCostForecast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Parameter")
                        .HasColumnType("bit");

                    b.Property<bool>("PercentageOrFixed")
                        .HasColumnType("bit");

                    b.Property<string>("ReportSheet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RowId");

                    b.ToTable("ReportFields", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.SalesValueByCategory", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerSqm")
                        .HasColumnType("float");

                    b.Property<bool>("ResidentialProperty")
                        .HasColumnType("bit");

                    b.Property<double>("Sold")
                        .HasColumnType("float");

                    b.Property<double>("SquareMeters")
                        .HasColumnType("float");

                    b.HasKey("RowId");

                    b.ToTable("SalesValueByCategories", "params");
                });

            modelBuilder.Entity("ForecastingModelParameters.Domain.SalesValueByPeriod", b =>
                {
                    b.Property<Guid>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplexProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quarter")
                        .HasColumnType("float");

                    b.Property<double>("SalesTargetInSqm")
                        .HasColumnType("float");

                    b.Property<double>("Year")
                        .HasColumnType("float");

                    b.HasKey("RowId");

                    b.ToTable("SalesValueByPeriods", "params");
                });
#pragma warning restore 612, 618
        }
    }
}
